services:
  backend:
    build:
      context: ./time-harmonie-back
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    # command: sh -c "npx prisma migrate deploy && npm run start:prod" // en attente de migration
    volumes:
      - ./time-harmonie-back:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - time_harmonie_network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - time_harmonie_network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - time_harmonie_network

volumes:
  postgres-data:
  
networks:
  time_harmonie_network: